### ISSUE TITLE
我在项目中用到了 Decorators ，但编译老是报错

### ISSUE THREAD

**Issue by weihong1028** [benjycui/bisheng#116]
```
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:

{
  "plugins": ["transform-decorators-legacy"]
}

The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.

   5 |
   6 | @observer
>  7 | class ModalComponent extends Component {
     | ^
   8 |
   9 |   modal = new Modal.Store();
```
我看到 `getBabelCommonConfig.js ` 这个文件是支持 Decorators，但不知道为什么就是没法编译通过
```
plugins: [
      require.resolve('babel-plugin-add-module-exports'),
      require.resolve('babel-plugin-transform-class-properties'),
      require.resolve('babel-plugin-transform-decorators-legacy'),
      require.resolve('babel-plugin-transform-object-rest-spread'),
    ]
```

**Comment by weihong1028** [comment]
最新版本 0.27.6

**Comment by benjycui** [comment]
Please provide a re-producible repo.

**Comment by weihong1028** [comment]
这个重现有点麻烦...抱歉。我提供更完整的报错信息，劳烦帮忙看看，一开始应该是我理解错了，代码里是可以正常使用 Decorators 的，不能正常使用的情况是在 demo/*.md 文件里。
![wx20171121-181204](https://user-images.githubusercontent.com/7336582/33066957-b7b45422-cee7-11e7-9d8a-d5119b0fc0b0.png)
```
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:

{
  "plugins": ["transform-decorators-legacy"]
}

The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.

   5 |
   6 | @observer
>  7 | class ModalComponent extends Component {
     | ^
   8 |
   9 |   modal = new Modal.Store();
  10 |
    at File.buildCodeFrameError (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-core/lib/transformation/file/index.js:427:15)
    at NodePath.buildCodeFrameError (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/path/index.js:140:26)
    at doError (/Users/harry/Project/quantex-design/node_modules/.6.24.1@babel-plugin-transform-decorators/lib/index.js:135:16)
    at PluginPass.ClassDeclaration (/Users/harry/Project/quantex-design/node_modules/.6.24.1@babel-plugin-transform-decorators/lib/index.js:161:9)
    at newFn (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/harry/Project/quantex-design/node_modules/.6.26.0@babel-traverse/lib/index.js:114:17)
```

**Comment by benjycui** [comment]
bisheng-plugin-react 需要单独配置，谢谢。

**Comment by benjycui** [comment]
See: https://github.com/benjycui/bisheng/tree/master/packages/bisheng-plugin-react#babelconfig-object
