### ISSUE TITLE
 document is not defined

### ISSUE THREAD

**Issue by git-lt** [benjycui/bisheng#149]
使用 --ssr 静态化时，一直报 ` document is not defined`，如果不带 --ssr 参数构建，一切正常

```
Created:  _site/components/DescriptionList/index.html
Created:  _site/components/DescriptionList-cn/index.html
ReferenceError: document is not defined
    at Object.DwSb (/Users/xx/work/xxx/antd-admin/node_modules/_bisheng@0.29.0@bisheng/tmp/index-ssr.5425f0.js:1:655484)
    at n (/Users/xx/work/MHC/antd-admin/node_modules/_bisheng@0.29.0@bisheng/tmp/index-ssr.5425f0.js:1:183)
```

**Comment by lili21** [comment]
这个跟你使用`document`的时机有关系。

可以将使用`document`的逻辑放到`componentDidMount`中。
